## https://k3d.io/v5.4.6/usage/configfile/
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: cluster1
agents: 0
ports:
  - port: 801:80
    nodeFilters:
      - loadbalancer
  - port: 4431:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik
        nodeFilters:
          - server:*
